import {TABLES,bits,encrypt,decrypt,expandKey,traceBlock,encodeText,decodeText,validateBits} from './sdes.js';
const $=id=>document.getElementById(id);
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let currentPage='cipher',mode='binary',decrypting=false,lastResult=null,lastTrace=null,traceStep=0,toastTimer;
const team=['王海丞','杨翔宇','刘焱'];
const hero=(eyebrow,title,subtitle)=>`<section class="hero"><div><span class="eyebrow">${eyebrow}</span><h1>${title}</h1><p>${subtitle}</p></div><div class="hero-art" aria-hidden="true"><i class="orb"></i><i class="orb"></i><i class="orb"></i><i class="lock"></i><i class="orb-dot"></i></div></section>`;
const head=(title,index)=>`<div class="card-head"><h2>${title}</h2><span class="card-index">${index}</span></div>`;
function toast(text){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),2500);}
function download(name,data){const blob=new Blob([typeof data==='string'?data:JSON.stringify(data,null,2)],{type:'application/json;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('文件已导出');}
async function copy(text){try{await navigator.clipboard.writeText(text);toast('已复制到剪贴板');}catch{toast('浏览器未允许复制，请手动选择结果。');}}
function showError(error){$('error').textContent=error.message||String(error);}
function clearError(){$('error').textContent='';document.querySelectorAll('[aria-invalid]').forEach(e=>e.removeAttribute('aria-invalid'));}
function milestones(){return `<div class="milestones">${['基本测试','交叉测试','扩展功能','暴力破解','封闭测试'].map((s,i)=>`<div class="milestone"><span class="num">0${i+1}</span><div><strong>${s}</strong><small>${['8-bit 加解密','异构平台验证','ASCII / UTF-8','完整密钥空间','碰撞空间分析'][i]}</small></div></div>`).join('')}</div>`;}
function keyMarkup(){return `<section class="card keys-card">${head('<span>⌘</span>密钥扩展','KEY SCHEDULE')}<p class="section-lead">10 位主密钥，派生两个轮密钥。</p><div class="key-path"><b>P10</b>→<b>LS-1</b>→<b>P8</b></div><div class="key-number"><span>第一轮子密钥 K₁</span><span>8 BITS</span></div><div class="key-value" id="k1">10100100</div><div class="key-path"><b>LS-1 结果</b>→<b>LS-2</b>→<b>P8</b></div><div class="key-number"><span>第二轮子密钥 K₂</span><span>8 BITS</span></div><div class="key-value" id="k2">01000011</div><div class="mini-note"><strong>两轮 Feistel 结构</strong><br>解密时反转子密钥顺序：K₂ → K₁。<br>LS-2 在 LS-1 的结果上继续左移 2 位。</div><div class="params"><div><strong>8</strong><small>分组长度 / bit</small></div><div><strong>10</strong><small>密钥长度 / bit</small></div><div><strong>2</strong><small>Feistel 轮数</small></div></div></section>`;}
function renderCipher(){
  lastResult=null;
  $('main').innerHTML=`<div class="page">${hero('THE CIPHER WORKBENCH','把比特，变成<span>秘密。</span>','探索简化 DES 的每一步。输入、运行，观察数据如何在两轮运算中变换。')}<div class="toolbar"><div class="segmented" aria-label="数据模式">${[['binary','二进制'],['ascii','ASCII 文本'],['utf8','UTF-8']].map(([id,name])=>`<button data-mode="${id}" class="${mode===id?'active':''}" aria-pressed="${mode===id}">${name}</button>`).join('')}</div><span class="tag green">● &nbsp; 课程标准 S-DES</span></div><div class="grid"><section class="card">${head('<span>◇</span>加密工作台','EXPERIMENT 01')}<div class="segmented" style="width:fit-content"><button id="encrypt-tab" class="${!decrypting?'active':''}" aria-pressed="${!decrypting}">加密 Encrypt</button><button id="decrypt-tab" class="${decrypting?'active':''}" aria-pressed="${decrypting}">解密 Decrypt</button></div><div class="field-head"><label for="data-input">${decrypting?'密文输入':'明文输入'}</label><span class="hint">${mode==='binary'?'8-BIT BINARY':decrypting?'HEX BYTES':mode==='ascii'?'ASCII STRING':'UTF-8 STRING'}</span></div>${mode==='binary'?`<input class="field" id="data-input" value="${decrypting?'10001100':'11010111'}" maxlength="8" autocomplete="off" spellcheck="false" aria-describedby="data-note">`:`<textarea class="field text" id="data-input" spellcheck="false" aria-describedby="data-note">${decrypting?'':mode==='ascii'?'Hello, S-DES!':'你好，S-DES 🔐'}</textarea>`}<div class="field-note" id="data-note">${mode==='binary'?'输入 8 个二进制位，保留开头的 0。':decrypting?'粘贴 Hex 密文字节，例如 8C 3F；字节间可使用空格。':mode==='ascii'?'支持 0–127 的 ASCII 字符，每个字节独立加密。':'UTF-8 编码后逐字节加密，支持中文与 emoji。'}</div><div class="field-head"><label for="key-input">主密钥</label><span class="hint">10-BIT SECRET KEY</span></div><div class="key-line"><input class="field" id="key-input" value="1010000010" maxlength="10" spellcheck="false" autocomplete="off"><button class="icon-button" id="random-key" title="生成随机密钥" aria-label="生成随机密钥">⤨</button></div><div class="input-foot"><button class="primary" id="run-cipher">${decrypting?'开始解密':'开始加密'} <span>→</span></button><button class="secondary" id="load-example">载入示例</button><span class="keyboard">⌘ / Ctrl ↵</span></div><div class="error" id="error" role="alert"></div><div class="result" id="cipher-result" aria-live="polite"></div></section>${keyMarkup()}</div><section class="card trace-card"> <div class="trace-head"><div><h2>计算过程 <span class="pill">可交互</span></h2><p>点击节点，展开每一步的真实中间值。</p></div><button class="secondary" id="export-trace">导出计算报告 ↗</button></div><div id="trace-content"></div></section>${milestones()}</div>`;
  document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;lastResult=null;renderCipher();});
  $('encrypt-tab').onclick=()=>{decrypting=false;renderCipher();};$('decrypt-tab').onclick=()=>{decrypting=true;renderCipher();};
  $('key-input').oninput=()=>{try{const keys=expandKey($('key-input').value);$('k1').textContent=keys.k1;$('k2').textContent=keys.k2;}catch{$('k1').textContent='········';$('k2').textContent='········';}};
  $('random-key').onclick=()=>{const n=new Uint16Array(1);crypto.getRandomValues(n);$('key-input').value=bits(n[0]%1024,10);$('key-input').oninput();toast('已生成 10 位随机密钥');};
  $('run-cipher').onclick=runCipher;$('load-example').onclick=()=>{$('key-input').value='1010000010';$('data-input').value=mode==='binary'?(decrypting?'10001100':'11010111'):decrypting?encodeText(mode==='ascii'?'Hello, S-DES!':'你好，S-DES 🔐','1010000010',mode):mode==='ascii'?'Hello, S-DES!':'你好，S-DES 🔐';runCipher();};
  $('export-trace').onclick=()=>{if(!lastResult) return toast('请先完成一次计算');download('sdes-calculation.json',{standard:'course-sdes-2026',team,tables:TABLES,...lastResult,trace:lastTrace});};
  lastTrace=null;traceStep=0;renderTrace();
  $('cipher-result').innerHTML='<div class="empty">结果将在这里呈现。<br><small>点击「开始计算」，或载入示例体验完整过程。</small></div>';
}
function runCipher(){
  clearError();const input=$('data-input').value,key=$('key-input').value,start=performance.now();
  try{
    validateBits(key,10,'密钥');const output=mode==='binary'?(decrypting?decrypt(input,key):encrypt(input,key)):(decrypting?decodeText(input,key,mode):encodeText(input,key,mode));
    const elapsed=performance.now()-start;lastResult={input,key,mode,decrypting,output,elapsedMs:elapsed,createdAt:new Date().toISOString()};
    let firstBlock;
    if(mode==='binary')firstBlock=input;else if(decrypting){const hex=input.replace(/\s/g,'');if(hex)firstBlock=bits(parseInt(hex.slice(0,2),16));}else if(input){firstBlock=bits(new TextEncoder().encode(input)[0]);}
    lastTrace=firstBlock?traceBlock(firstBlock,key,decrypting):null;
    const keys=expandKey(key);$('k1').textContent=keys.k1;$('k2').textContent=keys.k2;
    $('cipher-result').innerHTML=`<div class="result-head"><span><span class="status-dot"></span> &nbsp;${decrypting?'解密':'加密'}完成</span><button class="copy" id="copy-result">复制结果 ⧉</button></div>${mode==='binary'?`<div class="bits">${output.split('').map(n=>`<span class="bit">${n}</span>`).join('')}</div><div class="result-meta"><span>HEX &nbsp; ${parseInt(output,2).toString(16).toUpperCase().padStart(2,'0')}</span><span>DEC &nbsp; ${parseInt(output,2)}</span><span>${elapsed.toFixed(3)} ms</span></div>`:`<div class="output-text">${escape(output)||'（空字符串）'}</div><div class="result-meta"><span>${elapsed.toFixed(3)} ms</span><span>${decrypting?'TEXT OUTPUT':'HEX ENCODED'}</span></div>${!decrypting?`<div class="field-note">原始密文字符（控制字符可能不可见）：<code>${escape(output.split(' ').filter(Boolean).map(h=>String.fromCharCode(parseInt(h,16))).join(''))}</code></div>`:''}`}<div class="result-actions"><button class="text-link" id="roundtrip">${decrypting?'回填加密':'回填解密'} ↗</button><span class="hint">${mode==='binary'?'1 BLOCK':'BYTE-BY-BYTE'}</span></div>`;
    $('copy-result').onclick=()=>copy(output);$('roundtrip').onclick=()=>{decrypting=!decrypting;renderCipher();$('data-input').value=output;$('key-input').value=key;runCipher();};traceStep=0;renderTrace();
  }catch(error){showError(error);$('data-input').setAttribute('aria-invalid','true');}
}
function renderTrace(){
  if(!lastTrace){$('trace-content').innerHTML='<p class="empty">完成一次计算后，这里会展示真实的逐轮中间值。空文本不包含分组。</p>';return;}
  const t=lastTrace,steps=[['INITIAL PERMUTATION','初始置换 IP',t.ip],['FEISTEL ROUND 01','第一轮 fₖ',t.first.output],['SWAP HALVES','左右交换 SW',t.sw],['FEISTEL ROUND 02','第二轮 fₖ',t.second.output],['FINAL PERMUTATION','逆置换 IP⁻¹',t.output]];
  const detail=traceStep===1||traceStep===3?(traceStep===1?t.first:t.second):null;
  const items=detail?[['L / R',`${detail.left} / ${detail.right}`],['E/P 扩展',detail.ep],['⊕ 子密钥',detail.mixed],['S₁ / S₂',`${detail.s0} / ${detail.s1}`],['P4 置换',detail.p4],['轮输出',detail.output]]:traceStep===0?[['分组输入',t.input],['IP 表',TABLES.IP.join(' ')],['置换输出',t.ip]]:traceStep===2?[['交换前',t.first.output],['左半 → 右半',t.first.output.slice(0,4)],['右半 → 左半',t.first.output.slice(4)],['交换输出',t.sw]]:[['第二轮输出',t.second.output],['IP⁻¹ 表',TABLES.IP_INV.join(' ')],['最终输出',t.output]];
  $('trace-content').innerHTML=`<div class="flow">${steps.map(([sub,title,value],i)=>`${i?'<span class="flow-arrow">→</span>':''}<button data-step="${i}" class="${i===traceStep?'active':''}" aria-pressed="${i===traceStep}"><small>${sub}</small><strong>${title}</strong><code>${value}</code></button>`).join('')}</div><div class="trace-detail">${items.map(([title,value])=>`<div><small>${title}</small><code>${value}</code></div>`).join('')}</div><p class="trace-desc">${detail?`将右半部分扩展为 8 位，与 ${t.decrypting?(traceStep===1?'K₂':'K₁'):(traceStep===1?'K₁':'K₂')} = ${detail.key} 异或；S 盒压缩为 4 位，经 P4 置换后与左半部分异或。`:'位位置从左至右计数。'+(traceStep===2?'仅在两轮之间交换左右半部分。':'置换仅改变顺序，保留每个比特。')}${mode!=='binary'?' 当前展示文本的第一个字节。':''}</p>`;
  document.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>{traceStep=Number(b.dataset.step);renderTrace();});
}
function runWorker(kind,payload,progress){return new Promise((resolve,reject)=>{const worker=new Worker(new URL('./worker.js',import.meta.url),{type:'module'});worker.onmessage=e=>{if(e.data.progress!==undefined){progress?.(e.data.progress);return;}worker.terminate();e.data.error?reject(new Error(e.data.error)):resolve(e.data);};worker.onerror=()=>{worker.terminate();reject(new Error('后台计算无法启动，请通过 npm start 或线上网页运行。'));};worker.postMessage({id:1,kind,payload});});}
function renderCrack(){
  $('main').innerHTML=`<div class="page">${hero('EXPERIMENT 04 / KEY RECOVERY','小小密钥空间，<span>无处遁形。</span>','给定一个或多个明密文对，遍历全部 1024 个密钥，找出所有符合约束的候选。')}<div class="grid"><section class="card">${head('已知明密文对','KNOWN PAIRS')}<div class="field-head"><label>明文 · 8 bit</label><label>密文 · 8 bit</label></div><div id="pairs"></div><button class="text-link" id="add-pair">＋ 添加一组约束</button><div class="input-foot"><button class="primary" id="run-crack">搜索全部密钥 <span>→</span></button><button class="secondary" id="crack-example">多对示例</button></div><div id="error" class="error" role="alert"></div><div class="progress"><i id="crack-progress"></i></div><div id="crack-output" class="result" aria-live="polite"><span class="empty">候选密钥与真实计算耗时将在此呈现。</span></div></section><section class="card knowledge">${head('理解已知明文攻击','WHY IT WORKS')}<p>10 位密钥仅有 2¹⁰ 种可能。完整枚举不会漏掉符合输入的密钥。</p><div class="formula">E<sub>K</sub>(P₁) = C₁<br>E<sub>K</sub>(P₂) = C₂<br>…<br>K ∈ {0, 1}¹⁰</div><p>只有一组明密文对时，可能存在多个候选。添加更多明密文对通常可以缩小候选集合，但不能预先保证只剩一个密钥。</p><div class="mini-note">计算在 Web Worker 中完成，不阻塞页面。显示的耗时仅计入实际搜索过程，不人为延长进度条。</div><div class="params"><div><strong>1024</strong><small>完整密钥空间</small></div><div><strong>10</strong><small>密钥位数</small></div></div></section></div>${milestones()}</div>`;
  addPair('11010111','10001100');$('add-pair').onclick=()=>addPair();$('crack-example').onclick=()=>{$('pairs').innerHTML='';[0,1,2,42,215].forEach(p=>addPair(bits(p),encrypt(bits(p),'1010000010')));};$('run-crack').onclick=crack;
}
function addPair(plain='',cipher=''){
  if($('pairs').children.length>=32)return toast('最多支持 32 组约束');
  const row=document.createElement('div');row.className='pair';row.innerHTML=`<input class="field small pair-plain" maxlength="8" value="${plain}" aria-label="已知明文" placeholder="11010111" spellcheck="false"><span class="pair-arrow">→</span><input class="field small pair-cipher" maxlength="8" value="${cipher}" aria-label="已知密文" placeholder="10001100" spellcheck="false"><button aria-label="移除明密文对">×</button>`;row.querySelector('button').onclick=()=>{$('pairs').children.length>1?row.remove():toast('请保留至少一组明密文对');};$('pairs').append(row);
}
async function crack(){
  clearError();const button=$('run-crack'),output=$('crack-output'),progress=$('crack-progress');
  try{const pairs=Array.from($('pairs').children,row=>({plain:row.querySelector('.pair-plain').value,cipher:row.querySelector('.pair-cipher').value}));pairs.forEach(p=>{validateBits(p.plain,8,'明文');validateBits(p.cipher,8,'密文');});button.disabled=true;button.textContent='正在遍历密钥…';progress.style.width='12%';const report=await runWorker('crack',pairs);if(!output.isConnected)return;progress.style.width='100%';const r=report.result;
    output.innerHTML=`<div class="result-summary"><div><strong>${r.keys.length}</strong><small>符合约束的密钥</small></div><div><strong>${report.elapsedMs.toFixed(3)}</strong><small>实际计算耗时 / ms</small></div><div><strong>1024</strong><small>已测试密钥</small></div></div><div class="key-chips">${r.keys.map(key=>`<button class="key-chip" data-key="${key}" title="复制密钥">${key}</button>`).join('')||'<p class="empty">没有候选密钥，请检查明密文对是否使用相同密钥。</p>'}</div><p class="timestamp">开始 ${report.startedAt}<br>结束 ${report.endedAt}</p><div class="result-actions"><button class="text-link" id="export-crack">导出破解记录 ↗</button><span class="tag green">${r.keys.length?'SEARCH COMPLETE':'NO MATCH'}</span></div>`;
    output.querySelectorAll('[data-key]').forEach(b=>b.onclick=()=>copy(b.dataset.key));$('export-crack').onclick=()=>download('sdes-key-recovery.json',{team,pairs,...report});
  }catch(error){if(output.isConnected)showError(error);}finally{if(button.isConnected){button.disabled=false;button.innerHTML='搜索全部密钥 <span>→</span>';}}
}
function renderCollision(){
  $('main').innerHTML=`<div class="page">${hero('EXPERIMENT 05 / COLLISION ANALYSIS','不同的密钥，<span>相同的密文。</span>','固定一个明文，观察完整密钥空间的映射；再验证全部 256 个明文分组。')}<div class="grid"><section class="card">${head('密钥碰撞实验','CLOSURE TEST')}<div class="field-head"><label for="collision-input">固定明文</label><span class="hint">8-BIT BINARY</span></div><input class="field" id="collision-input" value="11010111" maxlength="8" spellcheck="false"><div class="input-foot"><button class="primary" id="run-collision">分析碰撞分布 <span>→</span></button><button class="secondary" id="run-all">全部明文测试</button></div><div id="error" class="error" role="alert"></div><div class="progress"><i id="collision-progress"></i></div><div id="collision-output" aria-live="polite"><p class="empty" style="margin-top:22px">运行实验，生成 256 格密文空间热力图。<br>每格代表一个密文，亮度表示映射到它的密钥数量。</p></div></section><section class="card knowledge">${head('碰撞为什么必然存在？','PIGEONHOLE PRINCIPLE')}<div class="formula">1024 个密钥 → 256 个密文<br>1024 / 256 = 4</div><p>对任意固定明文，将 1024 个密钥映射到最多 256 个密文。根据鸽巢原理，至少存在一个密文对应 4 个或更多密钥。</p><p>这说明<strong>不同密钥产生相同密文</strong>必然存在；并不意味着每个密文恰好对应 4 个密钥，也不意味着单个明密文对能确定唯一密钥。</p><div class="callout">当前结论针对固定明文下的密钥碰撞。若要判断两个密钥在所有明文上是否等价，需要比较完整的 256 项映射。</div></section></div>${milestones()}</div>`;
  $('run-collision').onclick=()=>analyze(false);$('run-all').onclick=()=>analyze(true);
}
async function analyze(all){
  clearError();const output=$('collision-output'),button=$('run-collision'),allButton=$('run-all'),progress=$('collision-progress');
  try{validateBits($('collision-input').value,8,'明文');button.disabled=allButton.disabled=true;progress.style.width='3%';const report=await runWorker(all?'all':'collision',$('collision-input').value,p=>{if(progress.isConnected)progress.style.width=`${p*100}%`;});if(!output.isConnected)return;progress.style.width='100%';const r=report.result;
    if(all){output.innerHTML=`<div class="result-summary"><div><strong>256 / 256</strong><small>存在碰撞的明文分组</small></div><div><strong>${report.elapsedMs.toFixed(2)}</strong><small>计算耗时 / ms</small></div></div><p class="section-lead">已计算 262,144 次加密映射。${r.allHaveCollisions?'全部明文均存在密钥碰撞，与鸽巢原理一致。':'存在异常，请查看报告。'}</p><div class="table-wrap"><table><thead><tr><th>明文</th><th>不同密文数</th><th>最大碰撞数</th></tr></thead><tbody>${r.rows.map(row=>`<tr><td>${row.plain}</td><td>${row.distinct}</td><td>${row.maxCollision}</td></tr>`).join('')}</tbody></table></div>`;}
    else {const counts=Array(256).fill(0);r.groups.forEach(g=>counts[parseInt(g.cipher,2)]=g.keys.length);output.innerHTML=`<div class="result-summary"><div><strong>${r.distinct}</strong><small>不同密文</small></div><div><strong>${r.maxCollision}</strong><small>最大碰撞数量</small></div><div><strong>${report.elapsedMs.toFixed(2)}</strong><small>耗时 / ms</small></div></div><div class="chart" aria-label="256 个密文的密钥数量热力图">${counts.map((n,i)=>`<div style="opacity:${n?0.18+0.82*n/r.maxCollision:0.035}" title="${bits(i)}：${n} 个密钥"></div>`).join('')}</div><div class="chart-label"><span>00000000 → 11111111</span><span>暗：少 &nbsp; 亮：多</span></div><div class="table-wrap" style="margin-top:20px"><table><thead><tr><th>密文</th><th>密钥数量</th><th>候选密钥（前 3 个）</th></tr></thead><tbody>${r.groups.map(g=>`<tr><td>${g.cipher}</td><td>${g.keys.length}</td><td>${g.keys.slice(0,3).join(', ')}${g.keys.length>3?' …':''}</td></tr>`).join('')}</tbody></table></div>`;}
    output.insertAdjacentHTML('beforeend','<div class="result-actions"><button class="text-link" id="export-collision">导出完整分析 ↗</button><span class="tag green">1024 KEYS / PLAINTEXT</span></div>');$('export-collision').onclick=()=>download('sdes-collision.json',{team,...report});
  }catch(error){if(output.isConnected)showError(error);}finally{if(button.isConnected){button.disabled=allButton.disabled=false;}}
}
function renderStandard(){
  const box=(name,data)=>`<div><span class="tag">${name}</span><table><tbody>${data.map(row=>`<tr>${row.map(v=>`<td>${bits(v,2)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
  $('main').innerHTML=`<div class="page">${hero('EXPERIMENT 02 / INTEROPERABILITY','同一份标准，<span>同一个结果。</span>','参数逐项核对课程文档。导出向量，与其他小组或独立参考实现比对。')}<div class="standard-grid"><section class="card">${head('课程算法参数','STANDARD 2026')}<div class="standard-table">${['P10','P8','IP','IP_INV','EP','P4'].map(name=>`<div><b>${name==='IP_INV'?'IP⁻¹':name}</b> ${TABLES[name].join(' ')}</div>`).join('')}</div><div class="sboxes">${box('S-box1 / S₁',TABLES.S0)}${box('S-box2 / S₂',TABLES.S1)}</div><div class="callout">石墨课程文档已完整给出 S-box2，公式与二进制表格一致。上表按文档逐项录入全部 16 个值。行由输入最外两位决定，列由中间两位决定。</div><a class="text-link" href="https://shimo.im/docs/m5kvdlMaKvcENy3X/" target="_blank" rel="noopener">打开课程文档 ↗</a></section><section class="card">${head('交叉验证工作台','CROSS-PLATFORM')}<p class="section-lead">参考向量采用 8 位明文、10 位密钥、8 位密文。导入其他程序导出的 JSON，逐项检查算法结果。</p><div class="formula">P = 11010111<br>K = 1010000010<br>C = 10001100</div><div class="input-foot"><button class="primary" id="export-vectors">导出 256 组向量 <span>↗</span></button><button class="secondary" id="import-vectors">导入并比对</button></div><input type="file" class="file-input" id="vector-file" accept=".json,application/json"><div id="error" class="error" role="alert"></div><div class="report-result" id="comparison" aria-live="polite"></div><div class="mini-note">格式：{"vectors": [{"plain": "11010111", "key": "1010000010", "cipher": "10001100"}]}<br>本仓库另附独立 Python 实现及实测交叉报告。真实组间测试需导入其他组的结果。</div></section></div><section class="card" style="margin-top:20px">${head('实验小组','TEAM')}<p class="section-lead" style="margin:0">王海丞 &nbsp; / &nbsp; 杨翔宇 &nbsp; / &nbsp; 刘焱<br>信息安全导论 · S-DES 算法程序实现 · 2026</p></section>${milestones()}</div>`;
  $('export-vectors').onclick=()=>download('sdes-cross-vectors.json',{standard:'course-sdes-2026',team,tables:TABLES,vectors:Array.from({length:256},(_,p)=>({plain:bits(p),key:'1010000010',cipher:encrypt(bits(p),'1010000010')}))});
  $('import-vectors').onclick=()=>$('vector-file').click();$('vector-file').onchange=async event=>{clearError();const file=event.target.files[0];if(!file)return;try{if(file.size>1048576)throw new Error('文件不得超过 1 MB。');const data=JSON.parse(await file.text()),vectors=Array.isArray(data)?data:data.vectors;if(!Array.isArray(vectors)||!vectors.length||vectors.length>10000)throw new Error('需要 1–10,000 项 vectors 数组。');let passed=0,failures=[];for(const v of vectors){validateBits(v.plain,8,'明文');validateBits(v.key,10,'密钥');validateBits(v.cipher,8,'密文');const actual=encrypt(v.plain,v.key);actual===v.cipher?passed++:failures.push({plain:v.plain,key:v.key,expected:v.cipher,actual});}$('comparison').textContent=`通过 ${passed} / ${vectors.length} 项\n${failures.length?`不一致 ${failures.length} 项\n`+failures.slice(0,5).map(f=>`${f.plain}: 收到 ${f.expected}，本程序 ${f.actual}`).join('\n'):'全部一致，可使用相同密钥互相加密和解密。'}`;}catch(error){showError(error);}finally{event.target.value='';}};
}
const renderers={cipher:renderCipher,crack:renderCrack,collision:renderCollision,standard:renderStandard};
function navigate(page){if(!renderers[page])page='cipher';currentPage=page;document.querySelectorAll('[data-page]').forEach(b=>{b.classList.toggle('active',b.dataset.page===page);b.setAttribute('aria-current',b.dataset.page===page?'page':'false');});$('breadcrumb-title').textContent={cipher:'加密 / 解密',crack:'密钥破解',collision:'封闭测试',standard:'算法标准 & 交叉测试'}[page];renderers[page]();}
document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{location.hash=b.dataset.page;});window.onhashchange=()=>navigate(location.hash.slice(1));
$('guide-button').onclick=()=>$('guide').showModal();$('close-guide').onclick=()=>$('guide').close();$('guide').onclick=e=>{if(e.target===$('guide')){const r=$('guide').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('guide').close();}};
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter'&&!$('guide').open){e.preventDefault();const b=$({cipher:'run-cipher',crack:'run-crack',collision:'run-collision'}[currentPage]);if(b&&!b.disabled)b.click();}});
navigate(location.hash.slice(1));
